<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Main Phone_id-c9e7ec2d-efca-4e4c-b3e3_f27c06</name>
   <tag></tag>
   <elementGuidId>41d8baa2-6c1a-49c1-a6aa-74a2d5bc2a7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-2-telephone14273edbd-ac1d-40d3-9fb2-095c621b552d-telephone1.fieldControl-phone-text-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-2-telephone14273edbd-ac1d-40d3-9fb2-095c621b552d-telephone1.fieldControl-phone-text-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main Phone</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>telephone1.fieldControl-phone-text-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Provide a telephone number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-x pa-fc pa-oi pa-am pa-br pa-dw pa-tf pa-ua pa-tt pa-tu pa-ql pa-ub pa-ae pa-af pa-hy pa-dd pa-ch pa-vi pa-vj pa-vk pa-qf pa-vl pa-qg </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>---</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-2-telephone14273edbd-ac1d-40d3-9fb2-095c621b552d-telephone1.fieldControl-phone-text-input&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-2-telephone14273edbd-ac1d-40d3-9fb2-095c621b552d-telephone1.fieldControl-phone-text-input']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-2-telephone14273edbd-ac1d-40d3-9fb2-095c621b552d-telephone1.fieldControl-phone-container']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-2-telephone14273edbd-ac1d-40d3-9fb2-095c621b552d-telephone1.fieldControl-phone-text-input' and @placeholder = 'Provide a telephone number' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
