<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Alex Bakeralextreyresearch.net619-555-01_b852f9</name>
   <tag></tag>
   <elementGuidId>45b0b97a-1833-41cb-8920-d57294902839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-3-primarycontactid270bd3db-d9af-4782-9025-509e298dec0a-primarycontactid.fieldControl-LookupResultsDropdown_primarycontactid_0_resultsContainer_0_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-3-primarycontactid270bd3db-d9af-4782-9025-509e298dec0a-primarycontactid.fieldControl-LookupResultsDropdown_primarycontactid_0_resultsContainer_0_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Alex Baker, alex@treyresearch.net</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-3-primarycontactid270bd3db-d9af-4782-9025-509e298dec0a-primarycontactid.fieldControl-LookupResultsDropdown_primarycontactid_0_instructionsToExpandListItem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>primarycontactid.fieldControl-LookupResultsDropdown_primarycontactid_resultsContainer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-ch pa-ao pa-a pa-z pa-e pa-wv pa-ts pa-cz pa-fj pa-wp pa-dp </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alex Bakeralex@treyresearch.net619-555-0127Trey ResearchSan Francisco</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-3-primarycontactid270bd3db-d9af-4782-9025-509e298dec0a-primarycontactid.fieldControl-LookupResultsDropdown_primarycontactid_0_resultsContainer_0_0&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-3-primarycontactid270bd3db-d9af-4782-9025-509e298dec0a-primarycontactid.fieldControl-LookupResultsDropdown_primarycontactid_0_resultsContainer_0_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-3-primarycontactid270bd3db-d9af-4782-9025-509e298dec0a-primarycontactid.fieldControl-LookupResultsDropdown_primarycontactid_0_tab_0']/li</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent records'])[1]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[2]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div[2]/ul/li</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-3-primarycontactid270bd3db-d9af-4782-9025-509e298dec0a-primarycontactid.fieldControl-LookupResultsDropdown_primarycontactid_0_resultsContainer_0_0' and (text() = 'Alex Bakeralex@treyresearch.net619-555-0127Trey ResearchSan Francisco' or . = 'Alex Bakeralex@treyresearch.net619-555-0127Trey ResearchSan Francisco')]</value>
   </webElementXpaths>
</WebElementEntity>
