<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Annual Revenue_id-c9e7ec2d-efca-4e4c-_618e89</name>
   <tag></tag>
   <elementGuidId>364e48c7-8340-41db-a07f-cedcae89dea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-5-revenue533b9e00-756b-4312-95a0-dc888637ac78-revenue.fieldControl-currency-text-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-5-revenue533b9e00-756b-4312-95a0-dc888637ac78-revenue.fieldControl-currency-text-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Annual Revenue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>revenue.fieldControl-currency-text-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-x pa-fc pa-oi pa-am pa-br pa-dw pa-tb pa-ts pa-qg pa-qh pa-tt pa-tu pa-ae pa-af pa-hy pa-dd pa-ch pa-vd pa-um </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>---</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-5-revenue533b9e00-756b-4312-95a0-dc888637ac78-revenue.fieldControl-currency-text-input&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-5-revenue533b9e00-756b-4312-95a0-dc888637ac78-revenue.fieldControl-currency-text-input']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-5-revenue533b9e00-756b-4312-95a0-dc888637ac78']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-c9e7ec2d-efca-4e4c-b3e3-f63c4bba5e4b-5-revenue533b9e00-756b-4312-95a0-dc888637ac78-revenue.fieldControl-currency-text-input' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
