<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Name_id-661157fe-2fc9-4eaa-83_bf213b</name>
   <tag></tag>
   <elementGuidId>9cf6d9a9-dc83-4e67-b7e0-0f84622f48b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_textInputBox_with_filter_new' and @placeholder = 'Look for records' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_textInputBox_with_filter_new']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid\.fieldControl-LookupResultsDropdown_parentcustomerid_1_textInputBox_with_filter_new</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_textInputBox_with_filter_new</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Account Name, Lookup</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>tree</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_textInputBox_with_filter_new</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Look for records</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-dn pa-uv pa-qd pa-qe pa-qg pa-qh pa-cn pa-dw pa-tb pa-uw pa-ux pa-uy pa-um </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_textInputBox_with_filter_new&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_textInputBox_with_filter_new']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_InputSearch']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div[3]/div[2]/div/div[2]/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_textInputBox_with_filter_new' and @placeholder = 'Look for records' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
