<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_id-661157fe-2fc9-4eaa-835f-5bfa_72c7b8</name>
   <tag></tag>
   <elementGuidId>04a3fc12-9f42-4501-826c-fed43900c64d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-text-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-text-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>emailaddress1.fieldControl-mail-text-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Provide an email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-x pa-fc pa-ok pa-am pa-br pa-dw pa-td pa-tz pa-tr pa-ts pa-qj pa-ua pa-ae pa-af pa-hy pa-dd pa-ch pa-vj pa-vk pa-vl pa-qd pa-vm pa-qe </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>---</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-text-input&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-text-input']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-container']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/section/div/div/div/div/div/div/div[2]/div/div[3]/div[2]/div/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-6-emailaddress1ada2203e-b4cd-49be-9ddf-234642b43b52-emailaddress1.fieldControl-mail-text-input' and @placeholder = 'Provide an email' and @type = 'text']</value>
   </webElementXpaths>
</WebElementEntity>
