<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Accounts</name>
   <tag></tag>
   <elementGuidId>44767a80-434c-4ff0-87fd-6a7e15f3113c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sitemap-entity-TrialApp_SubArea_Accounts']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sitemap-entity-TrialApp_SubArea_Accounts > div.pa-a.pa-am.pa-fc.pa-eu.pa-ds.pa-w.pa-gc.pa-gd.pa-fd.pa-fe.pa-ff.pa-fg.pa-fh.flexbox > div.pa-a.pa-fi.pa-fj.pa-w.pa-f.pa-o.pa-bc.pa-fk.flexbox > div.pa-bd.pa-e.pa-o.pa-fv.flexbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-bd pa-e pa-o pa-fv flexbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accounts</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sitemap-entity-TrialApp_SubArea_Accounts&quot;)/div[@class=&quot;pa-a pa-am pa-fc pa-eu pa-ds pa-w pa-gc pa-gd pa-fd pa-fe pa-ff pa-fg pa-fh flexbox&quot;]/div[@class=&quot;pa-a pa-fi pa-fj pa-w pa-f pa-o pa-bc pa-fk flexbox&quot;]/div[@class=&quot;pa-bd pa-e pa-o pa-fv flexbox&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='sitemap-entity-TrialApp_SubArea_Accounts']/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Accounts' or . = 'Accounts')]</value>
   </webElementXpaths>
</WebElementEntity>
