<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Katalon9029134885Las Vegas</name>
   <tag></tag>
   <elementGuidId>505066e8-a1f9-4aa8-9a1f-5bb3ca16b253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_resultsContainer_0_0' and (text() = 'Katalon9029134885Las Vegas' or . = 'Katalon9029134885Las Vegas')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_resultsContainer_0_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_resultsContainer_0_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Katalon, 9029134885</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_instructionsToExpandListItem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_resultsContainer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-ch pa-ao pa-a pa-z pa-e pa-zt pa-qb pa-cz pa-fj pa-wg pa-dp </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon9029134885Las Vegas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_resultsContainer_0_0&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_resultsContainer_0_0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_tab_0']/li</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent records'])[1]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[2]/following::li[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div[2]/ul/li</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'id-661157fe-2fc9-4eaa-835f-5bfa2f7b64f7-5-parentcustomerid270bd3db-d9af-4782-9025-509e298dec0a-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_1_resultsContainer_0_0' and (text() = 'Katalon9029134885Las Vegas' or . = 'Katalon9029134885Las Vegas')]</value>
   </webElementXpaths>
</WebElementEntity>
