<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lavona Field</name>
   <tag></tag>
   <elementGuidId>ce831488-f6cc-4229-b652-77083f163d89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='id-eaa6e6bb-4712-ec11-b6e7-00224820f09b-3-Component9657645-ListItemLabel_to_ecd95b39-3a1f-eb11-a813-000d3a33f3c3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id-eaa6e6bb-4712-ec11-b6e7-00224820f09b-3-Component9657645-ListItemLabel_to_ecd95b39-3a1f-eb11-a813-000d3a33f3c3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-eaa6e6bb-4712-ec11-b6e7-00224820f09b-3-Component9657645-ListItemLabel_to_ecd95b39-3a1f-eb11-a813-000d3a33f3c3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>Component9657645-ListItemLabel_to_ecd95b39-3a1f-eb11-a813-000d3a33f3c3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-an pa-ol pa-e pa-lx pa-ao pa-ee pa-om </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lavona Field</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-eaa6e6bb-4712-ec11-b6e7-00224820f09b-3-Component9657645-ListItemLabel_to_ecd95b39-3a1f-eb11-a813-000d3a33f3c3&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='id-eaa6e6bb-4712-ec11-b6e7-00224820f09b-3-Component9657645-ListItemLabel_to_ecd95b39-3a1f-eb11-a813-000d3a33f3c3']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='id-eaa6e6bb-4712-ec11-b6e7-00224820f09b-3-Component9657645-ListItemContent_ecd95b39-3a1f-eb11-a813-000d3a33f3c3']/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow-up call'])[4]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gabriela Christiansen'])[1]/following::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discuss Cold Coffee Machines'])[1]/preceding::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Miguel Garcia'])[1]/preceding::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lavona Field']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'id-eaa6e6bb-4712-ec11-b6e7-00224820f09b-3-Component9657645-ListItemLabel_to_ecd95b39-3a1f-eb11-a813-000d3a33f3c3' and (text() = 'Lavona Field' or . = 'Lavona Field')]</value>
   </webElementXpaths>
</WebElementEntity>
